In [1]:
%pylab
import numpy as np
import cv2
import matplotlib.pyplot as plt

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [2]:
#image = cv2.imread('Data/paisaje.jpg')
image = cv2.imread('Data/homer.png')
cv2.imshow('ImagenOriginal',image)
image.shape

(201, 251, 3)

In [3]:
# Reescalar la imagen
Nx, Ny = 512,512
image = cv2.resize(image,(Nx,Ny))

# Escala de grises

image_gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)

print(image_gray.shape)

# Conversion a punto flotante para hacer math
image_gray_float = np.float64(image_gray)

(512, 512)


In [4]:
cv2.imshow('ImageGray', image_gray)

In [5]:
FFT = np.fft.fft2(image_gray_float)
FFT = np.fft.fftshift(FFT)
FFTA = np.abs(FFT)
FFTLog = np.log10(FFTA)

In [6]:
cv2.imshow('EspectroFourier', np.uint8( 225*FFTLog/np.max(FFTLog)  ))

In [7]:
# Apli car un filtro 
F1 = np.arange( -0.5*Nx + 1, 0.5*Nx + 1, 1)
F2 = np.arange( -0.5*Ny + 1, 0.5*Ny + 1, 1)
[X,Y] = np.meshgrid(F1,F2)

In [8]:
D = np.sqrt(X**2+Y**2)
D = D/np.max(D)

In [9]:
print(D)

[[0.99609375 0.99414254 0.99219519 ... 0.99414254 0.99609375 0.99804879]
 [0.99414254 0.9921875  0.9902363  ... 0.9921875  0.99414254 0.99610141]
 [0.99219519 0.9902363  0.98828125 ... 0.9902363  0.99219519 0.99415789]
 ...
 [0.99414254 0.9921875  0.9902363  ... 0.9921875  0.99414254 0.99610141]
 [0.99609375 0.99414254 0.99219519 ... 0.99414254 0.99609375 0.99804879]
 [0.99804879 0.99610141 0.99415789 ... 0.99610141 0.99804879 1.        ]]


In [10]:
Huv = np.zeros((Nx,Ny))

D0 = 0.2
D1 = 0.6

for i in range(Nx):
    for j in range(Ny):
        if D[i,j] < D0:
            Huv[i,j] = 1
        if D[i,j] > D1:
            Huv[i,j] = 1

In [11]:
cv2.imshow('FiltroBaja', np.uint8(255*Huv))

In [12]:
Guv = Huv*FFT

GuvA = np.abs(Guv)

cv2.imshow('EspectroFourierFiltrado', np.uint8( 225*GuvA/np.max(GuvA)  ))

In [13]:
Gxy = np.fft.ifft2(Guv)
Gxy = np.abs(Gxy)

In [14]:
cv2.imshow('NuevaImagen', np.uint8( Gxy  ))